export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_ERROR = 'ADD_TO_WISHLIST_ERROR';


export const REMOVE_FROM_WISHLIST_REQUEST = 'REMOVE_FROM_WISHLIST_REQUEST';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_ERROR = 'REMOVE_FROM_WISHLIST_ERROR';

export const CLEAR_WISHLIST =  'CLEAR_WISHLIST';

export const GET_WISHLIST_PRODUCTS_REQUEST = 'GET_WISHLIST_PRODUCTS_REQUEST';
export const GET_WISHLIST_PRODUCTS_SUCCESS = 'GET_WISHLIST_PRODUCTS_SUCCESS';
export const GET_WISHLIST_PRODUCTS_ERROR = 'GET_WISHLIST_PRODUCTS_ERROR';








